/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppQuestionnairesRouteImport } from './routes/app/questionnaires'
import { Route as AppUpdatesRouteImport } from './routes/app/updates'
import { Route as AppUsersRouteImport } from './routes/app/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuestionnairesRoute = AppQuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/questionnaires': typeof AppQuestionnairesRoute
  '/app/updates': typeof AppUpdatesRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/questionnaires': typeof AppQuestionnairesRoute
  '/app/updates': typeof AppUpdatesRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/questionnaires': typeof AppQuestionnairesRoute
  '/app/updates': typeof AppUpdatesRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/questionnaires'
    | '/app/updates'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/questionnaires' | '/app/updates' | '/app/users' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/questionnaires'
    | '/app/updates'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/questionnaires': {
      id: '/app/questionnaires'
      path: '/questionnaires'
      fullPath: '/app/questionnaires'
      preLoaderRoute: typeof AppQuestionnairesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/updates': {
      id: '/app/updates'
      path: '/updates'
      fullPath: '/app/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppQuestionnairesRoute: typeof AppQuestionnairesRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppQuestionnairesRoute: AppQuestionnairesRoute,
  AppUpdatesRoute: AppUpdatesRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
